### ISSUE TITLE
Settings>Apps Crashes

### ISSUE THREAD

**Issue by eminp** [SuperiorOS-Devices/official_devices#34]
System crashes when click any app on apps section from settings. 

Device: Oneplus Nord
Build: SuperiorOS-Twelve-avicii-OFFICIAL-20220213-1020
Log: https://bin.kv2.dev/~620a0d3c410e7c32e669938d

**Comment by Darkstar085** [comment]
Fixed - https://github.com/SuperiorOS-Devices/changelogs/commit/a9b185e5226440bd644c1c3dd43aa493c2f09ffa
